mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace="polls")),

]

mysite/polls/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'^/$', index, name='index'),
    #127.0.0.1/polls/
    url(r'^(?P<question_id>[0-9]+)/$', detail, name="detail"),
    #127.0.0.1/polls/1
    url(r'^(?P<question_id>[0-9]+)/results$', results, name="results"),
    #127.0.0.1/polls/1/results
    url(r'^(?P<question_id>[0-9]+)/vote$', vote, name="vote"),
    #127.0.0.1/polls/1/vote

    url(r'^display_company$', display_company, name="display_company"),
    url(r'^register_company$', register_company, name="register_company"),
    url(r'^edit_company/(?P<pk>\d+)/$', edit_company, name="edit_company"),
    url(r'^delete_company/(?P<pk>\d+)/$', delete_company, name="delete_company"),
]

app_name="polls"

mysite/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length= 100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length= 200)
    votes = models.IntegerField(default= 0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

class Company(models.Model):
    name = models.CharField(max_length= 100)
    address= models.CharField(max_length= 200)
    telephone = models.IntegerField()
    email = models.CharField(max_length= 50)
    fax = models.IntegerField()
    vat_number = models.IntegerField()

    def __str__(self):
        return self.name

mysite/polls/forms.py
from django import forms
from .models import Company

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'address', 'telephone', 'email', 'fax', 'vat_number')

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question
from .models import Company
from .forms import *
from django.core.paginator import Paginator


# Create your views here.

def index(request):
    latest_questions = Question.objects.order_by('pub_date')[:5]
    context = {'latest_questions':latest_questions}
    return render (request, 'polls/index.html', context)

def detail(request, question_id):
    #return HttpResponse("This is the detail view of the question: %s" % question_id)
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/detail.html', {'question': question})
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice= question.choice_set.get(pk = request.POST['choice'])
    except:
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "Please select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def display_company(request):
    company = Company.objects.all()
    paginator = Paginator(company, 3)
    page = request.GET.get('page')
    company = paginator.get_page(page)
    context = {
        'company': company,
    }


    return render(request, 'polls/display_company.html', context)

def register_company(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST)

        if form.is_valid():
            form.save()
            #return render(request, 'polls/index.html', {'form': form})
            return redirect('polls:index')

    else:
            form = CompanyForm()
            return render(request, 'polls/register_company.html', {'form': form})

def edit_company(request, pk):
    item = get_object_or_404(Company, pk=pk)

    if request.method == "POST":
        form = CompanyForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('polls:index')
    else:
        form = CompanyForm(instance=item)
        return render(request, 'polls/edit_company.html', {'form': form})

def delete_company(request, pk):
    Company.objects.filter(id=pk).delete()
    company = Company.objects.all()
    context = {
        'company': company,
    }
    return render(request, 'polls/display_company.html', context)

mysite/polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" type = "text/css" href="{% static 'polls/bootstrap-4.3.1-dist/css/bootstrap.min.css' %}" />
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link rel="stylesheet" type = "text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
<hr>
<p> Header </p>
<hr>
{% include "polls/header.html" %}
<div class="jumbotron">
    <div class="container">

        {% block main_content %}
        {% endblock %}
            </div>
</div>
{% include "polls/footer.html" %}

</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block main_content %}

<h1> {{question.question_text}} </h1>
{% if error_message %} <p><strong> {{error_message}} </strong></p> {% endif %}

<form action = "{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value = "{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
    {% endfor %}
    <input type="submit" value="vote"/>
</form>


{% endblock %}

mysite/polls/templates/polls/display_company.html
{% extends 'polls/base.html' %}
{% block main_content %}

<table class="table table-hover">
    <thead>
     <tr>
         <th>Id</th>
         <th>Name</th>
         <th>Address</th>
         <th>Telephone</th>
         <th>Email</th>
         <th>Fax</th>
         <th>Vat Number</th>
     </tr>
    </thead>
    <tbody>

      {% for item in company %}
      <tr>
        <td>{{ item.pk }}</td>
        <td>{{ item.name }}</td>
        <td>{{ item.address }}</td>
        <td>{{ item.telephone }}</td>
        <td>{{ item.email }}</td>
        <td>{{ item.fax }}</td>
        <td>{{ item.vat_number }}</td>
          <td>
              <a href={% url "polls:edit_company" item.pk %} class="btn btn-warning btn-sm" role="button">Edit</a>
              <a href={% url "polls:delete_company" item.pk %} class="btn btn-danger btn-sm" role="button">x</a>
          </td>
      </tr>
    {% endfor %}
    </tbody>
</table>
 <div class="pagination">
              <span class="step-links">
        {% if company.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ company.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ company.number }} of {{ company.paginator.num_pages }}.
        </span>

        {% if company.has_next %}
            <a href="?page={{ company.next_page_number }}">next</a>
            <a href="?page={{ company.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
              </span>
          </div>
{% endblock %}

mysite/polls/templates/polls/edit_company.html
{% extends 'polls/base.html' %}
{% block main_content %}

<div class="container">
    <form method="POST">{% csrf_token %}

        {% for field in form %}
        <div class="form-group row">
            <label for="id_{{ field.name }}" class="col-2 col-form-label"> {{ field.label }}</label>
            <div class="col-10">
                {{ field }}
            </div>
        </div>

        {% endfor %}

        <button type="submit" class="btn btn-primary" name="button">Register Company</button>
    </form>
</div>
{% endblock %}

mysite/polls/templates/polls/footer.html
<hr>
<p>Footer</p>
<hr>

mysite/polls/templates/polls/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href={% url "polls:index" %}>Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
       <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
         <div class="dropdown-menu" aria-labelledby="dropdown01">
           <a class="dropdown-item" href="#">Action</a>
           <a class="dropdown-item" href="#">Another action</a>
           <a class="dropdown-item" href="#">Something else here</a>
         </div>
       </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block main_content %}

{% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
        <li><a href = {% url "polls:detail" question.id %}><b>{{question.question_text}}</b></a></li>
        {% endfor %}
    </ul>

{% else %}
    <p> You don't have any questions. Please add some</p>
{% endif %}

<div class= "button-group">
     <a href={% url "polls:register_company" %} class="btn btn-primary btn-md" role="button"> Register a Company</a>
     <a href={% url "polls:display_company" %} class="btn btn-primary btn-md" role="button"> Display all Companies</a>

</div>
{% endblock %}

mysite/polls/templates/polls/register_company.html
{% extends 'polls/base.html' %}
{% block main_content %}

<div class="container">
    <form method="POST">{% csrf_token %}

        {% for field in form %}
        <div class="form-group row">
            <label for="id_{{ field.name }}" class="col-2 col-form-label"> {{ field.label }}</label>
            <div class="col-10">
                {{ field }}
            </div>
        </div>

        {% endfor %}

        <button type="submit" class="btn btn-primary" name="button">Register Company</button>
    </form>
</div>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block main_content %}

<h1> {{question.question_text}} </h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> {{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes|pluralize}} </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}"> Vote Again</a>


{% endblock %}